FROM openwhisk/action-nodejs-v10:latest

RUN npm install aws-sdk fs perf_hooks sharp redis

ENV AWS_ACCESS_KEY_ID=AKIA56WI7EZGDCE3CQVR
ENV AWS_SECRET_ACCESS_KEY=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

